<?php

namespace IntraBundle\Repository;

/**
 * MatieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatieresRepository extends \Doctrine\ORM\EntityRepository
{
}
